### Create bad habit
POST localhost:9999/api/bad-habit/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjY2MjIxMjMsImlhdCI6MTY2NjYxODUyMywidXNlcl9pZCI6MX0.I0PA2UED2BBDUh5kjF8KmUZSN7yjUaPAjrVMa179Aiw
Content-Type: application/json

{
  "habit_category_id": 1,
  "equivalent_id": 5
}