### Create bad habit
POST localhost:9999/api/bad-habit/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjgwOTM5MzQsImlhdCI6MTY2NzQ5MzkzNCwidXNlcl9pZCI6MX0.NYz30UbBVgF1dR6YyNdHjTeHO3WA1mr5jaDRHGxJ8EA
Content-Type: application/json

{
  "habit_category_id":1,
  "equivalent_id": 9
}