###
GET localhost:9999/api/bad-habit/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjY2Mzk2NjgsImlhdCI6MTY2NjYzMzY2OCwidXNlcl9pZCI6MX0.L419ZAbRRYyhJZFrpaH-U4wLwPqXgAzJ2h6grhCWV7s
