### Create item
POST localhost:9999/api/item/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njc3MzA0ODQsImlhdCI6MTY2NzEzMDQ4NCwidXNlcl9pZCI6MX0.IE-M2EYaM8eKqexvNjnNTQa6dJUcyVi0yf2UkJemdk4
Content-Type: application/json

{
  "title": "asdds",
  "description": "Lkad",
  "body": "В клинике зaкончил, теперь пришёл подготовиться к вечерному уроку.Sasac"
}