### Create item
POST localhost:9999/api/item/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjY2MzkyMDgsImlhdCI6MTY2NjYzMzIwOCwidXNlcl9pZCI6MX0.Im9B15Swb-TPrsmwI6rcapm-g7VUv2lb85y2wshpUyQ
Content-Type: application/json

{
  "title": "asdds",
  "description": "Lkad",
  "body": "В клинике зaкончил, теперь пришёл подготовиться к вечерному уроку.Sasac"
}