### Get item By ID
GET localhost:9999/api/item/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjY2MzkyMDgsImlhdCI6MTY2NjYzMzIwOCwidXNlcl9pZCI6MX0.Im9B15Swb-TPrsmwI6rcapm-g7VUv2lb85y2wshpUyQ
