insert into categories(name)
values ('Smoking'),
       ('Porno dependence'),
       ('Hazard'),
       ('Internet dependence'),
       ('Gluttony'),
       ('Bite nails'),
       ('Gossip'),
       ('Attention dependence'),
       ('Reading'),
       ('Diary introduction'),
       ('Music'),
       ('Play guitar'),
       ('Write poems'),
       ('Walking'),
       ('Train'),
       ('Photogravure'),
       ('Singing'),
       ('Healthy eating'),
       ( 'Confidence' ),
       ('Close relations'),
       ('Self-appraisal'),
       ('Difficulty'),
       ('Junior'),
       ('Middle'),
       ('Senior'),
       ('Hands'),
       ('Legs'),
       ('Press'),
       ('Breast'),
       ('Back');
