port: "9999"

db:
  Host: "localhost"
  Port: 5432
  Username: "app"
  DBName: "zozh"

auth:
  TokenTTL: 1000m
  RefreshTokenTTL: 1200m

storage:
  Confidence: "D:\\storage\\Confidence\\"
  Difficulty: "D:\\storage\\Difficulty\\"
  CloseRelations: "D:\\storage\\Close relations\\"
  SelfAppraisal: "D:\\storage\\Self-appraisal\\"
