port: "9999"

db:
  Host: "localhost"
  Port: 5432
  Username: "app"
  DBName: "zozh"

auth:
  TokenTTL: 10000m
  RefreshTokenTTL: 12000m

storage:
  MentalCourse: "D:\\storage\\Mental course\\"
  BodyCourse: "D:\\storage\\Body course\\"
  Public: "D:\\storage\\Public\\"