### Create item
POST localhost:9999/api/item/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxNzI1OTEsImlhdCI6MTY2NjE3MTk5MSwidXNlcl9pZCI6MX0.1eCeEOVdLBDEMkyOhc1tSt4ZJfq8sNAFWhdVycMNcRU
Content-Type: application/json

{
"title": "Обед",
  "description": "sadas",
  "body": "В клинике закончил, теперь пришёл подготовиться к вечерному уроку"
}