### Create item
POST localhost:9999/api/item/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYyODgyMjMsImlhdCI6MTY2NjI4NzYyMywidXNlcl9pZCI6MX0.KrZ8UWCk1TElshGhMVUaxP3VfpoUlCE6rx5TcJMKqXM
Content-Type: application/json

{
  "title": "Обед",
  "description": "sadas",
  "body": "В клинике зaкончил, теперь пришёл подготовиться к вечерному уроку"
}