### delete item by ID
DELETE localhost:9999/api/item/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjU5NzEyODYsImlhdCI6MTY2NTkzNTI4NiwidXNlcl9pZCI6MX0.xe1luQmTaeoIXW8QiXWCIzVrGFzkEus9V9GFJXRb0FU