### create body course
POST localhost:9999/api/body
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njc1NjQ2NTgsImlhdCI6MTY2Njk2NDY1OCwidXNlcl9pZCI6MX0.p7Mpr3IY4RX_qcePXJeAAEn5sofAkjjwseVP6gQnT24
Content-Type: application/json

{
  "level_id": 23,
  "train_category_id": 29
}