### Create course
POST localhost:9999/api/mental
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjY3MTk0ODksImlhdCI6MTY2NjcxMzQ4OSwidXNlcl9pZCI6MX0.GV6xKQOjZhUAv_-sVoFfcpEO93AVgfwGqYMmqMW3hOc
Content-Type: application/json

{
  "mental_category_id": 1
}