name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Install dependencies
        run: |
        go get github.com/gin-gonic/gin 
        go get github.com/jackc/pgx 
        go get github.com/jackc/pgx/v5 
        go get github.com/lib/pq 
        go get github.com/spf13/viper
      - name: Build
        run: go build -v ./...
