name: CI-CD-Pipline-to-AWS-ElasticBeastalk

env:
  PACKAGE_NAME: "admin-application-packages"
  APPLICATION_NAME: "MyAdmin"
  ENVIRONMENT_NAME: "MyAdmin-env"
  DEPLOY_PACKAGES_NAME: "app_${{ github.sha }}.zip"
  REGION_NAME: "us-west-1"
  
on:
  push:
    branches:
      - master
      
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/ckeckout@v3
      
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGES_NAME }} ./ -x *.git*
